services:
  - type: web
    name: ARMY-backend
    env: node
    region: Frankfurt
    plan: free
    branch: main
    rootDir: functions
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: army-db
          property: connectionString

databases:
  - name: army-db
    engine: mysql  # Specify MySQL engine
    plan: free
